version: '3'
services:
  orders-service-example:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - romantic_ishizaka
      - infallible_wright
      - optimistic_hawking
  romantic_ishizaka:
    image: payments-service-example:latest
  infallible_wright:
    image: shipping-service-example:latest
  optimistic_hawking:
    image: products-service-example:latest

 