apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-example-dev-deployment
  labels:
    app: orders-service-example-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service-example-dev
  template:
    metadata:
      labels:
        app: orders-service-example-dev
    spec:
      containers:
        - name: orders-service-example-dev
          image: 346054926618.dkr.ecr.us-east-1.amazonaws.com/orders-service-example:orders-service-example-dev
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
spec:
  selector:
    app: ms-orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080